src/util.rs
Apply the escape only on windows, since it doesn't work on unix systems due to the escape sequence itself containing a space character.
This is a pull request to update the "escape-spaces-in-rustflags" and finally fix the issue on Windows.
The issue persists on Unix systems and it's not easy to solve. Anyways, paths containing whitespaces are uncommon on linux.
Tested on windows and should just work on linux, since no modifications are applied to the string.
=> Apply escape only on windows.

src/cargo.rs, src/sysroot.rs, src/util.rs
This is a PR originally filed by @AxelMontini  for `xargo`: https://github.com/japaric/xargo/pull/221
Below the originial PR description:
---
Fixes an error on windows where paths with whitespaces don't get escaped at all, causing the error error: multiple input filenames provided. In my case it happens because my Windows username is "Axel Montini" and xargo doesn't like the space in the middle.
This commit adds a function in utils to escape a string and replace spaces with %20 on windows or \ on other operative systems.
I haven't tested this on a Unix machine, but it seems to work on windows.
=> Escape spaces in rustflags

src/sysroot.rs
Fixes #4 
@qqwa Could you try whether this fixes your problem? You can install this version through:
```
cargo install --git https://github.com/rust-osdev/cargo-xbuild.git --branch unset-rustflags --force
```
=> Unset RUSTFLAGS when building sysroot

src/bin/cargo-xclippy.rs
After some more testing on a clean setup, this command actually works as intended. Kudos to the easy way of extending this crate 👍
=> Add xclippy command.

src/sysroot.rs
https://github.com/rust-lang/rust/pull/56092 changed the build process of the sysroot in the following way:
The compiler_builtins is now a normal crates.io crate: https://crates.io/crates/compiler_builtins. Since compiler_buitlins depends on libcore, but no sysroot exists yet when building liballoc, it has a special `rustc-std-workspace-core` feature that [overwrites the core dependency](https://github.com/rust-lang-nursery/compiler-builtins/blob/10f4f35f9670bb29715a8c1ec01284852d47ed35/Cargo.toml#L32) with an empty crates.io crate called [rustc-std-workspace-core](https://docs.rs/crate/rustc-std-workspace-core/1.0.0/source/Cargo.toml). This makes it possible to override the `core` dependency through a `patch` section in the Cargo.toml of liballoc.
For time reasons, this PR takes a …
=> The compiler_builtins library is now a crates.io dependency of alloc

CHANGELOG.md, src/cargo.rs, src/util.rs, src/xargo.rs
A sysroot with spaces does not work because of https://github.com/rust-lang/cargo/issues/6139. This PR adds a special error message for this case to prevent confusion. The error can be overridden by setting the `XBULD_ALLOW_SYSROOT_SPACES` environment variable.
=> Error when sysroot contains spaces

CHANGELOG.md, src/cargo.rs
This is useful for example when the default sysroot path contains spaces (see #32).
=> Add a `XBUILD_SYSROOT_PATH` environment variable to override sysroot path

CHANGELOG.md, src/cargo.rs, src/xargo.rs
The variable was added in an invalid way in #33, so that it was only used in RUSTFLAGS but not for building the sysroot. This PR fixes this.
=> Fix the new XBUILD_SYSROOT_PATH environment variable

src/bin/cargo-xdoc.rs, src/xargo.rs
By setting `RUSTDOCFLAGS` in addition to `RUSTFLAGS`, this patch allows `rustdoc` to inherit the modified sysroot. Closes #38.
(Figured I'd log `RUSTDOCFLAGS` in verbose mode too, in case future versions set it to something different than `RUSTFLAGS`, and since it's, well, verbose mode. Additionally, passing a reference to `Command:env` is totally equivalent to passing an owned string. Pretty minor patch.)
=> Add xdoc command

CHANGELOG.md, src/cargo.rs
Appending the flag a second time leads to a "Option 'sysroot' given more than once" error.
This problem occurs because the user might set the `RUSTFLAGS` environment manually, for example for [getting RLS to work](https://github.com/phil-opp/blog_os/issues/403#issuecomment-510145328).
=> Don't append a `--sysroot` argument to `RUSTFLAGS` if it already contains one

src/bin/cargo-xb.rs, src/bin/cargo-xc.rs, src/bin/cargo-xr.rs, src/bin/cargo-xt.rs
I've added these as separate binaries, since it requires the least amount of configuration and retains the ease of adding new subcommands. I had to change the "check if this was invoked as a cargo subcommand" logic a little to make it actually work when invoked as e.g. `cargo xc`.
Closes #41.
=> Add xb, xt, xc, and xr subcommands

CHANGELOG.md, src/lib.rs
Building for the host system target is often not intended.
It will also cause 'can't find crate for `std`' errors in build scripts of dependencies, which try to use the standard library. The reason is that [cargo applies the `RUSTFLAGS` environment variable also to build scripts in native compilation mode](https://github.com/rust-lang/cargo/blob/d9ff5762fe2a08d329fd869c6bb6b073796666cc/src/cargo/core/compiler/build_context/target_info.rs#L394-L395), thereby overriding the sysroot.
This issue was reported in https://github.com/phil-opp/blog_os/issues/403#issuecomment-529538864.
=> Print a warning when building for the host target

src/bin/cargo-xinstall.rs, src/bin/cargo-xpublish.rs
This is probably a niche use-case, but it is also a small PR. I plan to distribute an EFI application cross compiled with the `x86_64-unknown-uefi` target. But I would like to be able to give instructions to install and use these applications (via qemu) that are similar to installation of a normal binary available on cargo.io (i.e., you don't have to clone the source repo manually). So this PR adds an `xpublish` and `xinstall` command, tested using the `mythril` crate: https://crates.io/crates/mythril.
=> Add support for publishing and installing cross compiled crates

src/cli.rs, src/flock.rs, src/lib.rs, src/xargo.rs
I think the "waiting for file lock" message shouldn't be printed unconditionally. In this PR, I've chosen to use the existing verbose flag to turn it on. An alternative would be to use a quiet flag, just as cargo does, to turn it off. I'm not sure what's better.
The reason I ran into this is that I'm using the ninja build system which updates a single line on the console to show the executing commands. That is, only errors create newlines and stay visible. Therefore, I'm passing "-q" to cargo, but unfortunately this get's ignored by cargo-xbuild.
_Edit(phil-opp):_ We decided to add a `--quiet` flag instead of using the existing `--verbose` flag.
=> Add `--quiet` flag that suppresses "waiting for file lock" message

README.md, src/config.rs, src/help.txt, src/sysroot.rs
Added the option `panic_immediate_abort` to the configuration table. If this option is set to `true`, then the `core` crate will be compiled with the feature `panic_immediate_abort`. This new option is derived from #55.
Fixes #55.
=> Added new option to the configuration table (#55)

Cargo.lock, Cargo.toml, src/config.rs, src/lib.rs
If the Cargo.toml defines a workspace, then the `[package.metadata.cargo-xbuild]` may not be picked up, and the default configuration will be used silently . 
This is because the current code assumes that the root package is the first one: https://github.com/rust-osdev/cargo-xbuild/blob/master/src/config.rs#L21.
This PR infers the root package via `metadata.resolve`. It also updates `cargo-metadata` to the most recent version.
Fixes #54
=> Pick up xbuild config from workspace manifest

src/cli.rs, src/lib.rs
Closes #58.
Calling `build` directly allows use of `xbuild` as a library rather than needing to invoke it. This means for my build tool the user is not required to install `xbuild`. See https://github.com/paritytech/cargo-contract/pull/33/files#diff-ddd98095116f321c0aff2844e8cd3c55R106.
=> Make `fn build` and `Args` public to enable use as lib

src/config.rs, src/lib.rs
Since #57, we try to read the config from the root package of the workspace, instead of just defaulting to the first package. The problem with this is that the new code assumes that there is always a root _package_ in the workspace, which is not true when only a [_virtual manifest_](https://doc.rust-lang.org/cargo/reference/manifest.html#virtual-manifest) is used at the root.
With this pull request we no longer error for such workspaces. Instead, we emit a warning that no cargo-xbuild configuration is applied and use the default config. This isn't optimal, but there is no canoncial place to read the config from and I can't think of a better approach.
To ensure that future config related errors are easier to debug, this pull request also prints the underlying cause for config load errors. …
=> Fix: Not all projects have a root package 

src/cli.rs, src/lib.rs
This PR introduces an optional `config` parameter to the public `fn build`. This allows passing explicit config when using `xbuild` as a library (#58), which would otherwise require appending the config section to the `Cargo.toml`. If `None` is passed then it will attempt to resolve from the config file.
A second improvement is a new constructor for `Args`, which will add the explicitly specified args to the list of all args. This set of args is passed through to the internal invocation of `cargo`. Previously the constructor accepted the explicit args but they were not added to the list of all args.
=> Improvements to args and config for lib usage

src/bin/cargo-xfix.rs
Add `cargo xfix` command as described in issue #63.
Tested locally by running `cargo install` then `cargo xfix ...`.
=> Add `cargo xfix` command

README.md, src/sysroot.rs
=> Add an environment variable to keep the temp dir

src/cargo.rs, src/sysroot.rs
=> Enable lto for sysroot build to fix missing bitcode error

src/sysroot.rs
Ensures that the same versions of crates.io dependencies such as compiler_builtins are used.
Fixes #74
=> Respect Cargo.lock file for sysroot build

src/sysroot.rs
This is the same approach that rustc bootstrap uses: https://github.com/rust-lang/rust/blob/a2e0b48e6eef854521d3199ee9e327aab298f071/src/bootstrap/compile.rs#L235-L245
See https://github.com/japaric/xargo/issues/292 and #69 for more information.
=> Pass -Cembed-bitcode=yes instead of -Clinker-plugin-lto for sysroot build

src/config.rs, src/lib.rs
There does not seem to be a way to avoid that warning if a workspace is used. So, allow the user to disable the warning by passing --quiet to cargo-xbuild.
=> Don't print warning about missing root package in quiet mode.

src/cargo.rs, src/sysroot.rs
The `[profile.release]` section of the project's Cargo.toml is propagated into the xbuild, but may rely on Cargo features that require explicit enabling.  This PR also propagates any `cargo-features` from the project's Cargo.toml into the xbuild.
(I encountered this case when attempting to use [Cargo's new `strip` feature](https://github.com/rust-lang/cargo/pull/8246)).
=> Propagate `cargo-features` from project's Cargo.toml

README.md, src/rustc.rs, src/sysroot.rs
This updates `cargo-xbuild` to the new directory layout of `rust-src` component, which was introduced in https://github.com/rust-lang/rust/pull/73265.
Since this only works with nightlies newer than 2020-07-30, this is technically a **breaking change**.
=> Update cargo-xbuild to new rust directory layout

Cargo.lock, Cargo.toml, src/flock.rs, src/lib.rs
The use of [fs2](https://crates.io/crates/fs2) for file locking limits the platforms where cargo-xbuild can be built/installed.  Upstream cargo [was updated](https://github.com/rust-lang/cargo/commit/c04a87c1924246adef44c88bb64e5c7a8c60b823#diff-d4282c27d6736be951b98f456f02960a) to make the locking calls itself, as `fs2` is effectively unmaintained (and thus not merging patches to support new platforms).  This PR replicates that change, so cargo-xbuild is effectively freed of the platform constraints of `fs2`.
Thanks
=> Remove fs2 dependency for broader platform support

.github/workflows/cargo-build.yaml
Running `cargo build` on Linux, MacOS, and Windows should help catch build issues at least.
=> Add GitHub Action for cargo-build check

Cargo.lock, Cargo.toml, src/lib.rs
This should fix the breakage on Windows from #91  
Sorry about the extra hassle.
=> Fix winapi issues from flock() rework

README.md
Update the README to highlight the build-std-features flag cargo provides and how to use it to enable the mem feature in compiler-builtins.
=> Document build-std-features flag for Cargo's build-std.

src/lib.rs
This `expect()` causes my cargo subcommand to panic when building a project with invalid Cargo.toml metadata. E.g. specifying a dependency that cannot be downloaded, or invalid TOML syntax.
Transforming the error into a string instead of panicking provides a much more readable error message, and potentially allows callers to handle the failure gracefully.
Before:
```
$ cargo n64 build --ipl3 ~/bin/CIC-NUS-6102.bin -- --package hello-ipl3font
Building with cargo xbuild
thread 'main' panicked at 'cargo metadata invocation failed: CargoMetadata { stderr: "    Updating crates.io index\nerror: no matching package named `this-package-does-not-exist` found\nlocation searched: registry `https://github.com/rust-lang/crates.io-index`\nrequired by package `hello-ipl3font v0.1.0 …
```
=> Don't panic on metadata errors

src/sysroot.rs
Updated from #96:
> If the path pointed to by XARGO_RUST_SRC contains read-only Cargo
> lockfiles, then xbuild fails because the copies it makes and attempts to
> modify are also read-only.
=> Ensure copied Cargo.lock is writable
